version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha1234
      MYSQL_DATABASE: Quizzical
      MYSQL_USER: quizzicaladmin
      MYSQL_PASSWORD: qu1zz1c4l4dm1n
    volumes:
      - ./mariadb-data:/var/lib/mysql
  