version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha1234
      MYSQL_DATABASE: Quizzical
      MYSQL_USER: root
      MYSQL_PASSWORD: senha1234
    volumes:
      - ./mariadb-data:/var/lib/mysql
    ports:
      - '3306'

  keycloak:
    image: quay.io/keycloak/keycloak
    restart: always
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_DATABASE: Quizzical
      DB_USER: root
      DB_PASSWORD: senha1234
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - '8080'
    depends_on:
      - mariadb